build:
  image: centos:7
  commands:
    - yum install -y cmake soci git soci-mysql-plugin
    - git clone git://git.linphone.org/flexisip --recursive
    - cd flexisip
    - ./submodules/cmake-builder/prepare.py flexisip -DENABLE_SOCI=YES
